kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "helm.fullname" .}}-secret"
stringData:
  DOCKER_USERNAME: {{ .Values.app.dockerUsername }}
  DOCKER_PASSWORD: {{ .Values.app.dockerPassword }}